### ISSUE TITLE
Retrieving zone is allowed only by group

### ISSUE THREAD

**Issue by ipeychev** [PointDNS/nodejs-pointdns#5]
Hello,

Is it possible to retrieve a zone by its name, for example? It doesn't look so:
1. Listing zones is possible only [by group](https://github.com/cognetoapps/nodejs-pointdns/blob/e4743efe2e21096ba513e44c7125e71c7eb23969/pointdns.js#L26-L30).
2. Retrieving a zone is possible only [by its Id](https://github.com/cognetoapps/nodejs-pointdns/blob/e4743efe2e21096ba513e44c7125e71c7eb23969/pointdns.js#L45-L48).

How can I retrieve zone by its name?

**Comment by piotr-sokolowski** [comment]
Hello,
Actually API can return zone by either it's ID (when numeric) or by name so when you would pass zone name as 'zone_id' it would return the zone as well

**Comment by ipeychev** [comment]
Hello,

Okay, thanks for the information!

(A friendly piece of advice - you may consider changing this behaviour, it is odd. zone_id should accept only zone ID. Zone name should only accept zone name. The current kind of magic where zone_id could be zone ID or zone name only confuses developers).
